src/Entity/Developer.php
<?php

namespace App\Entity;

use App\Repository\DeveloperRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DeveloperRepository::class)]
class Developer
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $post_dev = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(nullable: true)]
    private ?int $phone = null;

    #[ORM\Column(nullable: true)]
    private ?int $age = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getPostDev(): ?string
    {
        return $this->post_dev;
    }

    public function setPostDev(?string $post_dev): static
    {
        $this->post_dev = $post_dev;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(?int $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAge(): ?float
    {
        return $this->age;
    }

    public function setAge(?float $age): static
    {
        $this->age = $age;

        return $this;
    }
}

src/Form/DeveloperType.php
<?php

namespace App\Form;

use App\Entity\Developer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DeveloperType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('post_dev')
            ->add('email')
            ->add('phone')
            ->add('age')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Developer::class,
        ]);
    }
}

src/Controller/DeveloperController.php
<?php

namespace App\Controller;

use App\Entity\Developer;
use App\Form\DeveloperType;
use App\Repository\DeveloperRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/developer')]
final class DeveloperController extends AbstractController{
    #[Route(name: 'app_developer_index', methods: ['GET'])]
    public function index(DeveloperRepository $developerRepository): Response
    {


        return $this->render('developer/all_developers.html.twig', [
            'developers' => $developerRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_developer_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $developer = new Developer();
        $form = $this->createForm(DeveloperType::class, $developer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($developer);
            $entityManager->flush();

            return $this->redirectToRoute('app_developer_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('developer/new.html.twig', [
            'developer' => $developer,
            'form' => $form,
        ]);
    }

    /*
    #[Route('/{id}', name: 'app_developer_show', methods: ['GET'])]
    public function show(Developer $developer): Response
    {
        return $this->render('developer/show.html.twig', [
            'developer' => $developer,
        ]);
    }
    */

    #[Route('/{id}/edit', name: 'app_developer_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Developer $developer, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(DeveloperType::class, $developer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_developer_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('developer/edit.html.twig', [
            'developer' => $developer,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_developer_delete', methods: ['POST'])]
    public function delete(Request $request, Developer $developer, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$developer->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($developer);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_developer_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/developer/_delete_form.html.twig
<form method="post" action="{{ path('app_developer_delete', {'id': developer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ developer.id) }}">
    <button class="btn">Delete</button>
</form>

templates/developer/all_developers.html.twig
{% extends 'layout/base.html.twig' %}
{% block main %}
    <h2>Все разработчики</h2>
    <div class="table-responsive">
      <table class="table table-striped table-sm">
        <thead>
          <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">Post_dev</th>
            <th scope="col">Email</th>
            <th scope="col">Phone</th>
            <th scope="col">Age</th>
            <th scope="col"></th>
            <th scope="col"><a class="btn btn-secondary" href="{{ path('app_developer_new') }}">Create new</a></th>
          </tr>
        </thead>
        <tbody>
        {% for developer in developers %}
          <tr>
            <td>{{ developer.id }}</td>
            <td>{{ developer.name }}</td>
            <td>{{ developer.postDev }}</td>
            <td>{{ developer.email }}</td>
            <td>{{ developer.phone }}</td>
            <td>{{ developer.age }}</td>
            <td>
                <a class="btn btn-warning" href="{{ path('app_developer_edit', {'id': developer.id}) }}">edit</a>
            </td>
            <td>
              <form method="post" action="{{ path('app_developer_delete', {'id': developer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                  <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ developer.id) }}">
                  <button class="btn btn-danger">Delete</button>
              </form>
            </td>
          </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>  
        </tbody>
      </table>
    </div>
{% endblock %}
{% block  leftPanelColor %}
  <script>
      var elem = document.getElementById('Developers');
      elem.style.color = 'red'; 
  </script>
{% endblock %}

templates/developer/edit.html.twig
{% extends 'layout/base.html.twig' %}

{% block main %}
    <h1>Edit Developer</h1>
    {{ form_start(form) }}
    {{ form_widget(form) }}
        <button class="btn btn-success">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}
{% endblock %}

templates/developer/new.html.twig
{% extends 'layout/base.html.twig' %}

{% block main %}
    <h1>Create new Developer</h1>
    {{ form_start(form) }}
    {{ form_widget(form) }}
        <button class="btn btn-success">Create Developer</button>
    {{ form_end(form) }}
{% endblock %}